[엘리] API 테스트/문서자동화 미션 제출합니다.
woowacourse/atdd-subway-favorite pull request #1
Opened 2020-05-26 04:17 UTC by YebinK

2020-05-26 14:31 UTC, young891221 requested changes
안녕하세요, 엘리!
미션 구현하느라 고생 많으셨습니다ㅎㅎ
미션구현은 크게 어렵지 않아(?) 테스트 위주로 봤는데 잘 작성해 주셨네요 👍 
몇 가지 코멘트 드렸습니다. 확인 부탁드릴게요!

2020-05-26 14:31 UTC, young891221 commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +            memberRepository.save(member);
member에 id가 있는데요. auto create인가요?
그렇다면 저장되서 반환되는 값을 반환해야 될 것 같은데 id가 필요없어서 바로 MemberResponse를 만드는지 궁금하네요.

2020-05-26 14:31 UTC, young891221 commented on src/main/java/wooteco/subway/web/exception/MemberControllerAdvice.java
> +public class MemberControllerAdvice {
현재는 정의되어 있는 에러처리만 되어 있는데요, 정의하지 않은 예외에 대해서도 잡아야 될 것 같습니다ㅎ

2020-05-26 14:31 UTC, young891221 commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        if (request.getMethod().equals("POST") && request.getRequestURI().equals("/members")) {
NPL일리는 없지만 상수값을 기준으로 비교하도록 습관을 들여주세요ㅎㅎ
ex) "POST".equals(request.getMethod())

2020-05-26 14:31 UTC, young891221 commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        if (request.getMethod().equals("POST") && request.getRequestURI().equals("/members")) {
요구사항에는 없지만 하나 연습용 미션을 드리자면...
검증이 불필요한 request가 늘어날 수 있어 보이는데요. 이를 좀 더 체계적으로 관리하도록 리펙토링 가능할까요?

2020-05-26 14:31 UTC, young891221 commented on src/test/java/wooteco/subway/doc/MemberDocumentation.java
>  public class MemberDocumentation {
FavoriteDocumentation 관련은 분리해 주세요. 어디로 갔나 열심히 찾아봤네요ㅎㅎ;;

2020-05-26 14:31 UTC, young891221 commented on src/test/java/wooteco/subway/acceptance/member/MemberAcceptanceTest.java
>      void manageMember() {
주석 디테일 칭찬합니다 💯

2020-05-29 06:16 UTC, YebinK commented on src/test/java/wooteco/subway/doc/MemberDocumentation.java
>  public class MemberDocumentation {
죄송합니다! 변경했습니다 :)

2020-05-29 07:02 UTC, YebinK commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +            memberRepository.save(member);
아! `memberRepository.save(member)`한 결과를 따로 Member 객체에 할당하지 않아도 기존에 존재하던 member에 id값이 들어가는 것을 확인하고 구현했습니다. :)

2020-05-29 07:03 UTC, YebinK commented on src/main/java/wooteco/subway/web/exception/MemberControllerAdvice.java
> +public class MemberControllerAdvice {
Exception.class를 잡는 exception handler를 추가했습니다!

2020-06-01 07:22 UTC, YebinK commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        if (request.getMethod().equals("POST") && request.getRequestURI().equals("/members")) {
현재 BearerAuthInterceptor의 preHandle 메소드는 로그인 후 토큰이 발급된 사용자의 토큰을 검증하는 로직인데요!
그래서 request의 header에 Authorization이 null인지를 체크해주었습니다.
그리고, `members`라는 uri는 로그인된 사용자에 한해 사용하는 단어가 맞다고 판단해 회원가입 uri를 `POST /members`에서 `POST /join`으로 변경했습니다.

혹시 의도하신 결과가 맞을까요? :)

2020-06-01 13:15 UTC, young891221 commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        if (request.getMethod().equals("POST") && request.getRequestURI().equals("/members")) {
음...변경하신걸로 처리하면 보안상 위험합니다. 헤더에 값이 없게끔 보내면 무조건 인증이 성공하니까요. 제가 의도한 부분은 `request.getMethod().equals("POST") && request.getRequestURI().equals("/members")`와 같이 특정한 URI의 경우 토큰 인증을 스킵하는데요. 이렇게 스킵가능한 URI가 늘어나면 if문이 증가할것 같아서 이를 이쁜 구조로 변경해 달라는 요구사항이였습니다ㅎㅎ

2020-06-01 13:17 UTC, young891221 commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        if (request.getMethod().equals("POST") && request.getRequestURI().equals("/members")) {
일단 이것은 수정하고 가야될것 같습니다ㅎㅎ
헤더에 값의 유무를 체크하는 것과 특정 URI를 체크하는 것은 보안적인 요소에서 중요한 부분이기에 기존 방식데로 처리하도록 수정부탁드립니다~!

2020-06-01 13:17 UTC, young891221 requested changes
안녕하세요 엘리!
리뷰 반영하느라 고생하셨습니다ㅎ
질문 주신 부분에 코멘트 추가하였습니다. 해당 부분만 수정하고 머지할게요~!

2020-06-02 16:46 UTC, YebinK commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        if (request.getMethod().equals("POST") && request.getRequestURI().equals("/members")) {
넵! 단순히 uri를 변경하면 된다고 판단했는데, 그렇게 해결되지 않는 경우도 분명 존재할 것 같네요!
사용자 타입을 요청별로 나누어 enum으로 변경하고, enum에서 해당 요청이 토큰 인증을 스킵해야 하는지 체크하도록 변경했습니다!

2020-06-03 12:09 UTC, young891221 approved these changes
엘리, 반영 잘해주셨네요 💯 
코멘트 반영하느라 고생 많으셨습니다~!
머지할게요:)

2020-06-03 12:09 UTC, merged