[코즈] API 테스트/문서자동화 미션 제출합니다.
woowacourse/atdd-subway-favorite pull request #12
Opened 2020-05-26 11:10 UTC by kouz95

잘 부탁드립니다!

2020-05-29 09:10 UTC, jeonghoon1107 requested changes
안녕하세요 코즈!
리뷰가 늦었습니다 ㅠㅠ
피드백 확인부탁드려요 :)
궁금한 부분은 언제든 DM주세요!

2020-05-29 09:10 UTC, jeonghoon1107 commented on src/main/java/wooteco/subway/domain/favorite/Favorite.java
> +    private String arrival;
테이블 설계를 다시 할 필요가 있어보이네요.
연관관계에 대해서 공부해보시면 좋을 것 같아요!

2020-05-30 09:08 UTC, kouz95 commented on src/main/java/wooteco/subway/domain/favorite/Favorite.java
> +    private String arrival;
안녕하세요 후니님! 리뷰 감사드립니다. 😊
사실, 이 부분에 대해서 여러 크루들과 많은 이야기를 나누었는데, 아직까지도 헷갈리는 부분이 남아있어 질문을 드리고 싶습니다.

현재 제가 즐겨찾기 기능에 대해 가능한 구조라고 생각하는 것은 다음과 같습니다.

1. Member가 즐겨찾기에 대한 정보를 Value Object의 형태로 가지는것.
```java
class Member {
	Set<Favorite> favorites;
}
```
`2. 
`3. Member가 Value Object의 형태로 Favorite을 연관 관계로 가지는것.`

2020-05-30 10:33 UTC, kouz95 commented on src/main/java/wooteco/subway/domain/favorite/Favorite.java
> +    private String arrival;
안녕하세요 후니님! 리뷰 감사드립니다. 😊

혹시, 말씀해주신 부분이 지하철역 이름으로 참조하는 것이 아닌, ID로 참조하는 것을 뜻하는게 맞을까요?

2020-05-30 10:41 UTC, jeonghoon1107 commented on src/main/java/wooteco/subway/domain/favorite/Favorite.java
> +    private String arrival;
네 맞습니다.
이름이 변경되면 추적하기 힘들겠네요!

2020-06-02 12:29 UTC, jeonghoon1107 requested changes
안녕하세요 코즈!
깔끔하게 구현 잘 하셨네요 👍 
피드백을 남겼으니 확인해주세요 :)

2020-06-02 12:29 UTC, jeonghoon1107 commented on src/main/java/wooteco/subway/service/member/MemberService.java
>      public void deleteMember(Long id) {
회원이 탈퇴하면 favorite은 어떻게 되나요?

2020-06-02 12:29 UTC, jeonghoon1107 commented on src/main/java/wooteco/subway/web/member/LoginMemberMethodArgumentResolver.java
> +            return MemberResponse.of(new Member());
빈 멤버를 주는 것이 의도된 동작인가요?

2020-06-02 12:29 UTC, jeonghoon1107 commented on src/main/java/wooteco/subway/web/member/LoginMemberMethodArgumentResolver.java
>          String email = (String) webRequest.getAttribute("loginMemberEmail", SCOPE_REQUEST);
다른 곳에서도 사용하는 것 같은데 loginMemberEmail 상수로 관리하면 좋겠네요 :)

2020-06-02 12:29 UTC, jeonghoon1107 commented on src/main/java/wooteco/subway/web/FavoriteController.java
> +        return ResponseEntity.created(URI.create("/favorites/" + favoriteId)).build();
favorites/{id} 라는 path가 존재하나요?

2020-06-02 12:29 UTC, jeonghoon1107 commented on src/main/java/wooteco/subway/web/ExceptionController.java
> +        System.out.println(exception.getMessage());
log를 이용해주세요 :)

2020-06-02 12:29 UTC, jeonghoon1107 commented on src/main/java/wooteco/subway/web/FavoriteController.java
> +    public ResponseEntity<List<FavoriteResponse>> showFavorites(
나의 즐겨찾기 역을 조회하는 것인가요?
path만 봐서는 어떤 것인지 구분이 잘 되지 않네요.
https://meetup.toast.com/posts/92 참고하시면 좋을 것 같아요!

2020-06-03 04:33 UTC, kouz95 commented on src/main/java/wooteco/subway/web/ExceptionController.java
> +        System.out.println(exception.getMessage());
어떤 기술을 사용하는것이 좋을까요?
검색 후 다양한 로그 출력 라이브러리가 있다는 것을 알게 되었고, 
java.util.logging 혹은 Log4j 같은 기술을 적용해 볼 수 있을것 같습니다!

2020-06-03 04:48 UTC, kouz95 commented on src/main/java/wooteco/subway/web/FavoriteController.java
> +    public ResponseEntity<List<FavoriteResponse>> showFavorites(
`/favorites/me` 라고 표현하면 어떨까 생각하고 있습니다.
어떻게 생각하시나요?

2020-06-08 15:39 UTC, jeonghoon1107 requested changes
안녕하세요 코즈!
피드백 반영 잘 해주셨네요 👍 
추가 피드백을 남겼으니 확인해주세요 :)

2020-06-08 15:39 UTC, jeonghoon1107 commented on src/main/java/wooteco/subway/service/member/MemberService.java
>              throw new RuntimeException("잘못된 패스워드");
잘못된 패스워드를 받은 것에 대해서 서버에러가 발생하였다고 피드백을 주어야하나요?

2020-06-08 15:39 UTC, jeonghoon1107 commented on src/test/java/wooteco/subway/service/favorite/FavoriteServiceTest.java
> +class FavoriteServiceTest {
mock말고 h2 db를 활용해 테스트해보면 어떨까요?

2020-06-13 02:19 UTC, jeonghoon1107 approved these changes
안녕하세요 코즈!
간단한 피드백 남겼으니 확인해주세요.
미션 진행하느라 고생하셨습니다 :)

2020-06-13 02:19 UTC, jeonghoon1107 commented on src/test/java/wooteco/subway/service/favorite/FavoriteServiceTest.java
> +    void setUp() {
tearDown메서드를 추가하여 항상 데이터를 초기화해주세요. (각 테스트가 다른 테스트의 데이터와 의존성 없이 서로 독립적으로 검증되도록)

2020-06-13 02:19 UTC, jeonghoon1107 commented on src/test/java/wooteco/subway/service/favorite/FavoriteServiceTest.java
> +        assertThat(favoriteService.findAll(memberId)).isNotEmpty();
empty를 검증하는 것 외에 데이터를 꺼내볼 수 있지 않을까요?
list assertion 등으로 검증 가능할 것 같아요

2020-06-13 02:20 UTC, merged