[예지니어스] API 테스트/문서자동화 미션 제출합니다.
woowacourse/atdd-subway-favorite pull request #15
Opened 2020-05-27 00:36 UTC by YejiAhn

안녕하세요
API 테스트/문서자동화 미션 제출합니다.
감사합니다 :)

2020-05-31 11:23 UTC, phs1116 requested changes
안녕하세요. 예지니어스!
리뷰어 화투입니다. 피드백이 늦어서 죄송해요. :)
구현은 깔끔하게 잘해주셨어요. 👍 
몇가지 피드백 추가했는데 참고 부탁드릴게요! :)

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/domain/favorite/Favorite.java
> +    }
Favorite을 유일하게 식별할 수 있는 식별자는 private Long id;아닐까요? :)

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/domain/line/LineStations.java
> +            });
재귀 말고 반복으로도 풀어내보면 더 좋을 것 같네요. :

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/domain/member/Member.java
> +    }
이런 로직 또한 일급컬렉션으로 풀어낼 수 있지 않을까요?

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/domain/member/Member.java
> +    Set<Favorite> favorites = new HashSet<>();
'즐겨찾기'라는 도메인 컨텍스트가 Member에 속하는가? Member가 직접 참조해도 괜찮을지는 조금 고민이 필요해보여요. :) 
지금은 도메인의 범위가 작아서 괜찮을 수 있겠지만, 가면 갈수록 Member의 범위가 커져서 단일 책임 원칙을 위배할 수도 있거든요.
Favorite에서는 Member를 표현하는 값객체를 가지고 있어 두 객체를 격리하고,
Member는 Favorite자체는 모르도록 하여 책임을 분리할 수도 있을 것 같아요. :)


https://nesoy.github.io/articles/2018-07/DDD-Bounded-Context

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/domain/station/Stations.java
> +            .orElseThrow(RuntimeException::new);
`이펙티브 자바 아이템 아이템 73. 추상화 수준에 맞는 예외를 던지라 75. 예외의 상세 메시지에 실패 관련 정보를 담으라`
RuntimeException 외에 예외에 메시지를 담아보아요! :)

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/service/line/LineStationService.java
>          lineRepository.saveAll(lines);
Line과 LineStation을 전부 다 가져오지 않고도 풀어낼수도 있지 않을까요?

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +        memberRepository.deleteFavoriteById(favoriteId);
MemberService에서 즐겨찾기와 회원 관리 등 책임 요소가 많은데 분리해볼수 있지 않을까요? :)

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/service/path/GraphService.java
> +            .filter(it -> Objects.nonNull(it.getPreStationId()))
jects.nonNull(it.getPreStationId() -> 첫 역이라는 의미의 메서드로 추상화할수 있지 않을까요? :)
도메인적으로 조금 더 명확하게 드러나기도 하구요.

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/service/path/PathService.java
> +            .orElseThrow(RuntimeException::new);
`이펙티브 자바 아이템 아이템 73. 추상화 수준에 맞는 예외를 던지라 75. 예외의 상세 메시지에 실패 관련 정보를 담으라` :)
RuntimeException으로 던지는 부분들 한번씩 점검해주면 좋을 것 같아요.

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/web/Advice.java
> +public class Advice {
클래스 명을 조금 더 구체적으로 표현해주면 좋을 것 같아요! :

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/web/member/FavoriteController.java
> +            favoriteRequest.getTargetStationId());
세가지 로직을 하나의 기능으로 보고 모두 서비스에서 담당해도 되지 않을까요? :)

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/web/Advice.java
> +    public ResponseEntity<String> exceptionHandler(Exception e) {
ExceptionHandler또한 여러개 설정이 가능하니 이를 감안하고 네이밍을 해주신는게 좋을 것 같아요.
혹은 인자라도 Exception -> SubwayException로 설정해줘도 좋을 것 같구요. :)

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        String token = authExtractor.extract(request, "bearer");
"bearer" 같은 값은 상수로관리해줘도 좋을 것 같네요. :)

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        }
isCreateMemberMethod, isLoginMethod 처럼 토큰 존재 검증등으로 메서드를 분리할 수 있지 않을까요?

2020-05-31 11:23 UTC, phs1116 commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
>      }
url에 대한 설정은 interceptor에 등록 시 설정이 가능해요. :) 
여기서 설정해도 될 것 같아요.

2020-06-09 07:36 UTC, YejiAhn commented on src/main/java/wooteco/subway/service/line/LineStationService.java
>          lineRepository.saveAll(lines);
LineRepository에서 `DELETE FROM LINE_STATION WHERE station_id = :id` 쿼리를 통해 해당 역의 id를 가지고 있는 구간을 지워줄까 생각했었는데요, 그렇게 할 경우 다음 구간의 전 역 id를 이전 구간의 역 id로 업데이트시켜주는 애플리케이션 로직이 닿지 못하기 때문에 removeLineStationById라는 애플리케이션 로직을 꼭 거쳐야될 것 같습니다.

2020-06-12 14:51 UTC, phs1116 approved these changes
안녕하세요, 예지니어스!
구현 깔끔하게 잘해주셨어요. :)
간단한 코멘트와 함께 이번 과제 머지할게요.
구현하시느라 수고 많으셨어요!

2020-06-12 14:51 UTC, phs1116 commented on src/main/java/wooteco/subway/service/line/LineStationService.java
>          lineRepository.saveAll(lines);
그 부분에 대한 로직도 적은 쿼리로 처리할수도 있을 것 같기는 한데요,
도메인 주도적으로 작성한다면 지금 방식도 괜찮을 것 같아요. :)

2020-06-12 14:51 UTC, phs1116 commented on src/main/java/wooteco/subway/domain/member/Member.java
> +    }
Favorite을 가져가기로 했다면 추상화 관점에서 일급컬렉션 작성도 좋았을 것 같네요. :)

2020-06-12 14:51 UTC, phs1116 commented on src/main/java/wooteco/subway/web/ExceptionController.java
>          return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(e.getMessage());
시스템 예외 메시지가 클라이언트에게 직접 노출되는건 별로 좋지 않아요.
Sl4fj등으 사용해 에러 로그를 찍고 클라이언트에겐 임의의 메시지를 전달해주는게 좋을 것 같네요. :)

2020-06-12 14:52 UTC, merged