[오렌지] API 테스트/문서자동화 미션 제출합니다.
woowacourse/atdd-subway-favorite pull request #21
Opened 2020-05-27 06:26 UTC by YerinCho

감사합니다 :)

2020-05-27 12:17 UTC, kingbbode requested changes
안녕하세요 :)
전체적인 리뷰 전 테이블 설계를 먼저 고민하기 위해 코멘트 작성해두었습니다.
확인 부탁드려요!

2020-05-27 12:17 UTC, kingbbode commented on src/main/java/wooteco/subway/domain/favorite/FavoriteStation.java
> +    private String target;
먼저 테이블에 대한 설계가 다시 필요하겠네요 :)
source 와 target 의 역이름을 그대로 저장하고 있네요.

`신천`이란 역을 만들고 즐겨찾기를 추가하였다고 할 때, 신천역 이름이 잠실새내역으로 변경이 되면 사용자의 즐겨찾기는 어떻게 될까요?
데이터 저장소에 저장되는 모든 데이터는 데이터의 키를 중심으로 관리되어야 합니다 :)

`FavoriteStation` 이 `Station` 과 연관관계를 맺도록 재설계 부탁드립니다.

2020-05-28 11:32 UTC, YerinCho commented
테이블에 id로 저장하면 이름으로 id를 찾는 과정이 반드시 필요해지더라고요. 
사실상 역 이름이 바뀌는 현상이 자주 발생하지 않는다고 생각했습니다. 그래서 이름을 저장하게 되면 테이블을 조회하는 횟수가 줄어들거라 생각했는데, 이 점에서는 어떻게 생각하시는지 궁금합니다!

2020-05-30 14:35 UTC, kingbbode requested changes
안녕하세요 :)
코멘트 작성해두었습니다.
확인 부탁드려요!

2020-05-30 14:35 UTC, kingbbode commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +        } catch (DbActionExecutionException e) {
`DbActionExecutionException` 은 모든 데이터베이스 예외에서 반환됩니다.
이 예외로 항상 중복된 이메일로인한 예외라는 것을 보장할 수 있을까요?
`cause` 을 활용하여 조금 더 정확하게 처리해보는 것이 어떨까요?

2020-05-30 14:35 UTC, kingbbode commented on build.gradle
> +    runtimeOnly 'com.h2database:h2'
의존성의 버전을 직접 명시해주었네요.
스프링부트에서 관리해주고 있는 버전관리에 대한 부분을 찾아보시면 좋을 듯 합니다 .

2020-05-30 14:35 UTC, kingbbode commented on src/main/java/wooteco/subway/service/favorite/FavoriteService.java
> +        return FavoritesResponse.of(favoriteStations);
쿼리가 여러번 발생하는 비효율이 있네요 :)
데이터베이스 조회의 비용은 꽤 큽니다. 최소한의 쿼리를 사용하도록 개선해보는게 어떨까요?

2020-05-30 14:35 UTC, kingbbode commented on src/main/java/wooteco/subway/service/favorite/FavoriteService.java
> +    }
중복된 즐겨찾기가 등록되지 못하도록 개선해보는 것은 어떨까요?

2020-05-30 14:47 UTC, kingbbode commented
현재 일어나지 않는 먼 미래의 일을 대비하여 과한 확장성을 고려한 설계를 오버 엔지니어링이라고 하며, 이것은 개발자들에게 굉장히 견제해야하고, 인식해야될 일이기도 합니다. 현재의 비지니스를 고려한 최소한의 모델링을 고려하신 점은 좋습니다.

그러나 현재의 비지니스만을 고려하여 미래에 생길 변화를 대응하지 못하는 설계를 하는 것은 잘못된 설계가 됩니다. 이 또한 개발자들이 굉장히 견제해야하고, 인식해야할 일 입니다.

앞으로도 위 둘 사이에서 항상 선택을 하셔야할텐데요. 명확한 선택에 대한 정답이나 기준은 없지만, 저장소에 저장되는 데이터에 대해서는 최소한으로 지켜야할 것들이 있습니다. 

그 중 하나로 말씀드리는 것이 데이터의 무결성입니다. 이 것은 데이터 모델링에서 중요한 요소로, 동일한 데이터에 대해 서로 다른 결과를 발생시키는 일이 없어야 한다는 점이고, 현재 직면했던 문제도 데이터의 무결성이 훼손된다는 것을 말씀드릴 수 있겠네요.

데이터에 대한 무결성을 확보하지 못한 데이터 모델링은 가까운 미래의 변경사항을 쉽게 반영하지 못하게 될 가능성이 점점 커지게 됩니다. 

(데이터 무결성은 검색으로 많은 데이터를 보실 수 있을 것이기에 따로 자료는 첨부하지 않을게요!)

2020-06-07 04:37 UTC, YerinCho commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +        } catch (DbActionExecutionException e) {
예외 메시지를 일반적인 내용으로 바꾸고 cause도 함께 받도록 변경했습니다.
cause를 함께 받으면 예외가 발생했을 때  더 자세하게 나오네요! 👍

2020-06-07 04:41 UTC, YerinCho commented on build.gradle
> +    runtimeOnly 'com.h2database:h2'
spring-restdocs-asciidoctor 와 spring-restdocs-mockmvc 같은 경우는 io.spring.dependency-management에서 버전 관리를 해주네요! 
버전 관리를 해주는 의존성인 경우엔 특정 버전이 꼭 필요한 경우가 아니면 굳이 버전을 명시하지 않아도 편하게 사용할 수 있겠네요 😄

2020-06-07 04:42 UTC, YerinCho commented on src/main/java/wooteco/subway/service/favorite/FavoriteService.java
> +        return FavoritesResponse.of(favoriteStations);
어차피 시간복잡도는 n으로 똑같으니, 
전체 역을 한번 조회하고 조회해서 가져온 역 리스트에서 source와 target 이름을 찾도록 변경했습니다!

2020-06-07 04:51 UTC, YerinCho commented on src/main/java/wooteco/subway/service/favorite/FavoriteService.java
> +    }
member 가 favoriteStations 객체를 이미 갖고 있어서 member.contain(FavoriteStation) 메소드에서 저장하려는 즐겨찾기가 이미 등록된 즐겨찾기인지의 여부를 이미 검증하고 있긴 합니다!

혹시 제가 잘못 이해하고 있거나 개선사항이 필요한 부분이면 알려주세요 ㅠㅅㅠ..

2020-06-07 05:42 UTC, YerinCho commented
자세한 답변 감사합니다.☺️☺️

특히 지금 이 문제에서 두드러지는 건 참조 무결성을 위반하는 문제인 것 같네요. 
오버엔지니어링을 별로 안 좋아해서 현재 요구사항을 위주로 생각해서 설계하는 편이었는데, 무결성을 해친다.. 무결성에 대해서는 알지도 못하고 생각해 본 적도 없었어서 새로운 관점으로도 보게 되네요! 감사합니다. 역시 설계는 항상 쉽지 않은 문제네요. :)

혹시 제가 피드백 이해를 잘 못해 잘못 반영한 부분이 있다면 말씀해주세요. 😊

2020-06-07 15:39 UTC, kingbbode approved these changes
고생 많으셨습니다! 이만 머지할게요 :)

2020-06-07 15:40 UTC, merged