[히로] API 테스트/문서 자동화 미션 제출합니다.
woowacourse/atdd-subway-favorite pull request #22
Opened 2020-05-27 07:08 UTC by hotheadfactory

:)

2020-05-28 12:30 UTC, hongsii requested changes
안녕하세요 히로~
요구사항 구현을 잘 해주셨네요 👍 
몇 가지 피드백 드렸으니, 참고하셔서 반영해주세요!

2020-05-28 12:30 UTC, hongsii commented on src/main/java/wooteco/subway/domain/member/Favorites.java
> +    public List<FavoriteResponse> toFavoriteResponses(List<Station> stations) {
도메인(Entity)이 클라이언트에 의존하는 DTO를 아는 것이 적절할까요?

2020-05-28 12:30 UTC, hongsii commented on src/main/java/wooteco/subway/domain/member/Member.java
> +    }
즐겨찾기 추가는 `Favorite` 객체를 인자로 받으나, `removeFavoriteById` 는 id를 받아서 내부에서 `Favorite` 객체를 생성하고 있습니다. 매개변수를 일관되게 바꿔보면 어떨까요?

2020-05-28 12:30 UTC, hongsii commented on src/main/java/wooteco/subway/service/member/FavoriteService.java
> +    public boolean ifFavoriteExist(FavoriteRequest favoriteRequest, Member member) {
`if-` 보단 `existsFavorite` 로 네이밍하면 좀 더 자연스러울 것 같아요

2020-05-28 12:30 UTC, hongsii commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +        return memberRepository.findByEmail(email).orElseThrow(() -> new InvalidAuthenticationException("ILLEGAL_ACCESS"));
36라인과 45라인은 똑같이 이메일로 회원을 찾는데 예외 문구가 다른 이유가 있을까요?

2020-05-28 12:30 UTC, hongsii commented on src/main/java/wooteco/subway/web/member/ExceptionController.java
> +public class ExceptionController {
서버 개발자가 예상하지 못한 에러(예외)가 발생하면 클라이언트로 어떤 에러가 응답될까요?
이와 관련된 처리를 해보면 좋을 것 같아요!

2020-05-28 12:30 UTC, hongsii commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +            // TODO: 2020/05/25 if문 처리 없이 연결을 제어하는 방법 고민
요 TODO도 처리해주시면 좋을 것 같아요~

2020-05-28 12:30 UTC, hongsii commented on src/test/java/wooteco/subway/doc/FavoriteDocumentation.java
> +                        fieldWithPath("destinationName").type(JsonFieldType.STRING).description("The destination station's name")
자주 사용되는 필드는 메서드로 추출해보면 어떨까요?

2020-05-28 12:30 UTC, hongsii commented on src/test/java/wooteco/subway/domain/member/MemberTest.java
> +public class MemberTest {
즐겨찾기에 대한 예외 케이스도 테스트로 작성하면 좋을 것 같아요

2020-05-28 12:30 UTC, hongsii commented on src/test/java/wooteco/subway/service/member/MemberServiceTest.java
> +    // TODO: 2020/05/20 update/remove에 대한 테스트는 어떻게 하나요? 질문해보기
Mock 라이브러리에서 제공하는 검증 메서드를 활용하면 테스트할 수 있습니다.

* https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#1

2020-05-28 12:30 UTC, hongsii commented on src/test/java/wooteco/subway/acceptance/favorite/FavoriteAcceptanceTest.java
> +public class FavoriteAcceptanceTest extends AcceptanceTest {
잘못된 토큰으로 요청하는 케이스도 테스트로 작성해보면 어떨까요?

2020-05-28 12:30 UTC, hongsii commented on src/main/java/wooteco/subway/domain/member/Favorites.java
> +public class Favorites {
일급 콜렉션 👍

2020-05-28 12:30 UTC, hongsii commented on src/main/java/wooteco/subway/service/member/FavoriteService.java
> +        Favorites favorites = new Favorites(member.getFavorites());
매번 `Favorites` 객체 를 사용하는 쪽에서 생성하기 보다 `Member` 내에서 반환하도록 바꿔보면 어떨까요?

2020-06-04 05:28 UTC, hotheadfactory commented on src/main/java/wooteco/subway/domain/member/Favorites.java
> +    public List<FavoriteResponse> toFavoriteResponses(List<Station> stations) {
FavoriteService의 책임으로 바꾸었습니다!!

2020-06-04 10:36 UTC, hotheadfactory commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +            // TODO: 2020/05/25 if문 처리 없이 연결을 제어하는 방법 고민
WebMvcConfig에서 특정 URI에 인터셉터를 걸어주면 어떤 HTTP 메서드를 쓰느냐에 관계 없이 전부 인터셉터가 걸리기 때문에 이를 막기 위해 인터셉터에 분기를 사용하는 상황입니다. (POST /members는 회원가입 시 사용되는 메소드이기에 토큰 검사를 하면 안됩니다) 

이 경우에 REST함을 포기하고 회원가입을 별도 URI로 분리하는 게 맞을까요? 아니면 다른 방법이 있을까요?

2020-06-06 10:12 UTC, hotheadfactory commented on src/test/java/wooteco/subway/service/member/MemberServiceTest.java
> +    // TODO: 2020/05/20 update/remove에 대한 테스트는 어떻게 하나요? 질문해보기
감사합니다 :)

2020-06-08 22:13 UTC, hongsii approved these changes
피드백 반영을 잘 해주셨네요! 👍 
미션 진행하시느라 고생 많으셨습니다! 머지할게요 :)

2020-06-08 22:13 UTC, hongsii commented on src/main/java/wooteco/subway/web/member/ExceptionController.java
> +        return ResponseEntity.status(500).body(ErrorResponse.of(e));
스프링에서는 다양한 상수를 제공하니 이를 활용해도 좋을 것 같아요!
`HttpStatus.INTERNAL_SERVER_ERROR`

2020-06-08 22:13 UTC, hongsii commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +            // TODO: 2020/05/25 if문 처리 없이 연결을 제어하는 방법 고민
말씀하신대로 BearerAuthInterceptor 인터셉터를 용도 맞게 사용하려면 분기를 작성하는 것은 좋지 않습니다.
지금처럼 필요하다면 REST에 맞지 않더라도 URI 분리하는 것이 좋습니다.
또는 특정 prefix가 붙은 URI를 사용하면 해당 인터셉터를 태우도록 설정할 수도 있을 것 같습니다.
ex)
/members -> interceptor 미적용
/secure/members -> 인터셉터를 태울 prefix에만 interceptor 적용

2020-06-08 22:13 UTC, merged