[쪼밀리] API 테스트/문서자동화 미션 제출합니다.
woowacourse/atdd-subway-favorite pull request #46
Opened 2020-05-28 11:31 UTC by SujinEmilyCho

안녕하세요 홍시, 쪼밀리입니다!
리뷰 잘 부탁드려요😊

2020-05-29 16:15 UTC, hongsii requested changes
안녕하세요 쪼밀리!
전반적으로 요구사항을 잘 구현해주셨네요 👍 
몇 가지 피드백 드렸으니, 확인하셔서 반영해주세요~

2020-05-29 16:15 UTC, hongsii commented on src/main/java/wooteco/subway/domain/favorite/Favorite.java
> +    Long station;
코드를 사용하다 보면 네이밍만 보고 Station 타입이라고 오해를 불러일으킬 수 있을 듯 합니다. 명확하게 id를 뒤에 붙이는 건 어떨까요?

2020-05-29 16:15 UTC, hongsii commented on src/main/java/wooteco/subway/service/favorite/FavoriteService.java
> +            .orElseThrow(() -> new RuntimeException("해당하는 역이 존재하지 않습니다."));
위에 `InvalidStationIdException` 을 사용 중이니 해당 예외를 사용해도 좋을 것 같아요

2020-05-29 16:15 UTC, hongsii commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +			.orElseThrow(() -> new RuntimeException("해당 이메일이 존재하지 않습니다."));
RuntimeException 보다는 IllegalArgumentException 과 같이 구체적인 성격을 나타낼 수 있는 예외를 사용하면 더 좋을 것 같아요!
그리고 `findMemberByEmail(..)`을 재사용하면 어떨까요?

2020-05-29 16:15 UTC, hongsii commented on src/main/java/wooteco/subway/web/GlobalControllerAdvice.java
> +    @ExceptionHandler(Exception.class)
4xx, 5xx 코드가 의미하는 것은 무엇일까요? 그리고 전체 예외를 핸들링하는 곳에선 어떤 코드로 처리하는 것이 적절할까요?
이 곳에서 처리되는 로직은 어떤 것일까요? 를 고민해보시면 어떨까요?

2020-05-29 16:15 UTC, hongsii commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        String extractedAuth = authExtractor.extract(request, "Bearer");
문자열은 상수로 관리해보면 어떨까요?

2020-05-29 16:15 UTC, hongsii commented on src/main/resources/templates/admin/index.html
>            </li>
역 관리와 구간 관리도 admin 주소로 바뀌어야 하지 않을까요?

2020-05-29 16:15 UTC, hongsii commented on src/test/java/wooteco/subway/doc/FavoriteDocumentation.java
> +            ),
문서에서 반복해서 쓰일 헤더는 재사용해보면 어떨까요?

2020-05-29 16:15 UTC, hongsii commented on src/test/java/wooteco/subway/service/favorite/FavoriteServiceTest.java
> +        // Todo: 스트림으로인해 순서를 알 수 없는 경우 명확하게 테스트 할 수 있는 방법?
assertj에서 컬렉션 검증문을 제공하니 이를 활용해보면 어떨까요?

* https://github.com/joel-costigliola/assertj-examples/blob/master/assertions-examples/src/test/java/org/assertj/examples/IterableAssertionsExamples.java

2020-06-02 03:35 UTC, SujinEmilyCho commented on src/test/java/wooteco/subway/service/favorite/FavoriteServiceTest.java
> +        // Todo: 스트림으로인해 순서를 알 수 없는 경우 명확하게 테스트 할 수 있는 방법?
우와, 너무 유용한 자료에요! 감사감사합니다!😊
extracting과 containsOnly를 사용해서 테스트 코드 수정했습니다 : )

2020-06-05 17:28 UTC, hongsii requested changes
우선 피드백이 늦어서 죄송합니다 ㅠㅠ
이전 피드백 반영을 깔끔하게 잘 해주셨네요! 👍 
간단한 피드백 남겼으니, 여기까지 반영해주세요 :)

2020-06-05 17:28 UTC, hongsii commented on src/main/java/wooteco/subway/domain/member/Member.java
> +        if (findFavorite(favorite).isPresent()) {
`Collection` 을 활용하기 위해 `equals(...)` 를 구현해도 괜찮을 것 같아요! 
지금도 괜찮은 구조니 이 피드백은 참고만 해주세요~

2020-06-05 17:28 UTC, hongsii commented on src/main/java/wooteco/subway/domain/station/Station.java
> +    @JsonSerialize(using = LocalDateTimeSerializer.class)
도메인과 클라이언트 모델의 구현은 분리하는 것이 좋습니다.
그 이유는 클라이언트(혹은 API)마다 요구사항 구현이 다를 수 있으며, 클라이언트가 변경되면 도메인도 변경이 되기 때문에 변경에 취약한 구조가 됩니다.
클라이언트에서 사용할 모델을 따로 만들어보면 어떨까요?

2020-06-05 17:28 UTC, hongsii commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        }
아직 TODO가 남았네요! 리팩토링을 진행해보시면 어떨까요?

2020-06-05 17:28 UTC, hongsii commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
>          request.setAttribute("loginMemberEmail", email);
여기도 상수로 선언할 수 있지 않을까요?

2020-06-09 10:58 UTC, SujinEmilyCho commented on src/main/java/wooteco/subway/domain/member/Member.java
> +        if (findFavorite(favorite).isPresent()) {
맞아요! 처음에는 페어랑 `equals()`를 구현하려고 했었어요~😊

여기서는 preStationId와 stationsId가 동일하면 같은 즐겨찾기라고 판단해야하는데, 실제 Favorite 클래스는 id 멤버변수도 가지고 있어요. 이 때 prestationId, stationId를 기준으로 equals를 작성하면 다른 곳에서 Favorite API를 사용할 때 예상치 않은 결과를 가지고 올 수 있을 것이라고 생각했어요!

그리고, 현재 Favorite은 Entity인데 equals를 구현해야한다면 id를 기준으로 equals를 구현해야하지 않나 싶기도 하구요...!

2020-06-11 12:49 UTC, hongsii approved these changes
피드백 반영을 깔끔하게 잘 해주셨네요! 👍 
미션 진행하시느라 고생많으셨습니다! 머지할게요 :)

2020-06-11 12:49 UTC, hongsii commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        if (Objects.isNull(handlerMethod.getMethodAnnotation(RequireAuth.class))) {
어노테이션 활용 👍

2020-06-11 12:49 UTC, merged