[두강] API 테스트/문서 자동화 미션 제출합니다.
woowacourse/atdd-subway-favorite pull request #47
Opened 2020-05-28 12:14 UTC by ParkDooWon

감사합니다! :)

2020-05-29 12:08 UTC, jaeyeonling requested changes
안녕하세요 두강!
요구사항에 맞게 잘 구현해주셨어요 💯 
소소한 피드백 몇개 남겨드렸으니 확인하고 반영해주세요~

2020-05-29 12:08 UTC, jaeyeonling commented on build.gradle
> +    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc:2.0.4.RELEASE'
```suggestion
    asciidoctor 'org.springframework.restdocs:spring-restdocs-asciidoctor'
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
```

plugins에서 'io.spring.dependency-management'가 어떠한 역할을 하는지 공부해보세요~

2020-05-29 12:08 UTC, jaeyeonling commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +            .orElseThrow(IllegalArgumentException::new);
IllegalArgumentException으로 해당 예외 상황을 나타낼 수 있을까요?

2020-05-29 12:08 UTC, jaeyeonling commented on src/main/java/wooteco/subway/web/ExceptionController.java
> +			.status(HttpStatus.BAD_REQUEST.value())
```suggestion
			.status(HttpStatus.BAD_REQUEST)
```

따로 value를 입력하지 않아도 괜찮겠네요.

2020-05-29 12:08 UTC, jaeyeonling commented on src/main/java/wooteco/subway/web/ExceptionController.java
> +	@ExceptionHandler(EntityNotFoundException.class)
EntityNotFoundException을 공통적으로 사용하고 있는데요.
해당 예외처리에 모든 응답을 "NOT_EXISTENT_DATA"으로 준다면 클라이언트는 어떠한 Entity를 찾지 못했는지 알기 힘들지 않을까요?

2020-05-29 12:08 UTC, jaeyeonling commented on src/main/java/wooteco/subway/web/FavoritesController.java
> +@RequestMapping("members/favorites")
해당 URL 규칙은 RESTful하지 않은 것 같습니다~
리소스에 대한 고유 식별자를 추가해주면 좋을 것 같아요!

2020-05-29 12:08 UTC, jaeyeonling commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        if (!jwtTokenProvider.validateToken(token)) {
```suggestion
        if (jwtTokenProvider.isInvalidToken(token)) {
```

부정문은 가독성을 해칠 수 있습니다.
Objects.isNull과 Objects.nonNull이 존재하는 이유에 대해 고민해보아요.

2020-05-30 09:10 UTC, ParkDooWon commented on src/main/java/wooteco/subway/web/ExceptionController.java
> +			.status(HttpStatus.BAD_REQUEST.value())
불필요한 메서드 사용을 삭제했습니다!

2020-05-30 09:53 UTC, ParkDooWon commented on src/main/java/wooteco/subway/web/member/interceptor/BearerAuthInterceptor.java
> +        if (!jwtTokenProvider.validateToken(token)) {
가독성을 고려하여 부정문을 제거하도록 수정했습니다. :)

2020-05-30 10:30 UTC, ParkDooWon commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +            .orElseThrow(IllegalArgumentException::new);
제가 해당 예외 상황에 대해서 잘 이해하지 못했습니다.
말씀하신 해당 예외 상황이 `존재하지 않는 이메일을 입력한 경우`와 `이메일은 존재하지만 비밀번호가 일치하지않는 경우`를 사용자에게 구분해서 알려주는 것인가요?

지금 저의 코드는 이메일을 잘못입력한 경우와 이메일은 맞지만 비밀번호가 틀린 경우를 구분하지 않고 둘 중 하나가 틀린 경우에 `로그인에 실패했습니다`라는 공통 메세지를 사용자에게 보여주는데, 이렇게 하지말고 이메일을 잘못 입력했으면 `존재하지 않는 이메일입니다`를 사용자에게 보여주고 이메일은 맞지만 비밀번호를 잘못 입력했으면 `비밀번호가 틀렸습니다`를 사용자에게 구분해서 보여줘야하는 것인가요?

2020-05-31 13:50 UTC, ParkDooWon commented on src/main/java/wooteco/subway/web/ExceptionController.java
> +	@ExceptionHandler(EntityNotFoundException.class)
찾지 못한 Entity가 어떤 Entity인지를 알 수 있도록 각자 다른 Exception을이 발생하도록 수정했습니다.

처음에는 Station, Line, LineStation에 대해서 데이터가 없는 경우 모두 `EntityNotFoundException`을 발생시키고, 전달하는 에러 메세지만 다르게 해서 `getMessage()`를 할 때 서로 다른 메세지를 전달하여 Entity를 구분하려고 했는데, 내부 메세지를 그대로 노출하는 것은 보안상 좋지 않다는 피드백을 보고 각각의 Exception을 만들었습니다. 
이렇게 각 Entity에 대해서 커스텀 Exception을 만드는 것이 더 좋은 방법인가요? 아니면 더 좋은 방법이 있을까요?

2020-06-01 14:56 UTC, ParkDooWon commented on src/main/java/wooteco/subway/web/FavoritesController.java
> +@RequestMapping("members/favorites")
URI만 보고도 어떤 작업을 하는지 명확하게 알 수 있도록 보다 RESTful하게 URI를 변경했습니다! :)

`@PathVariable`을 사용하지 않고 `@LoginMember`를 사용해도 Member를 구하여 사용할 수 있는데 그렇게 하지않는 이유는 Member는 식별자를 통해 구할 수 있는 Resource여서 그런건가요? 🤔 

궁금한 것이 `@PathVariable`을 사용하는 API를 만들기 위해서는 항상 Member의 ID를 별도로 저장하여 가지고 있어야할텐데, 토큰 안에 저장된 이메일을 통해 어떤 사용자인지 알아낼 수 있음에도 굳이 Member Id를 보관하는 작업을 하는 이유가 궁금합니다. RESTful한 API를 만드는 것이 이러한 수고로움을 감내할 만큼 중요한 작업인지 궁금합니다. :)

2020-06-01 15:14 UTC, ParkDooWon commented on build.gradle
> +    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc:2.0.4.RELEASE'
`dependency-management 플러그인`은 현재 사용하고 있는 Spring Boot의 버전에 맞게 사용하고자 하는 라이브러리의 버전을 자동으로 가져오는 역할을 하고, 사용하려는 의존성을 관리해주는 플러그인이라고 공부했습니다. :)

아래의 글을 보고 학습했습니다.
https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/
https://dingue.tistory.com/17

2020-06-02 13:28 UTC, jaeyeonling commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +            .orElseThrow(IllegalArgumentException::new);
앗 아닙니다!
해당 예외처리는 멤버를 찾지 못하면 발생하는 예외인데요.
별도 메시지 없이 `IllegalArgumentException`을 발생시키는게 맞을까? 라는 고민이였습니다 ㅎㅎ
해당 상황을 나타낼 수 있는 메시지를 추가하거나, 익셉션을 분리해보면 어떨까요?

2020-06-02 13:36 UTC, jaeyeonling commented on src/main/java/wooteco/subway/web/ExceptionController.java
> +	@ExceptionHandler(EntityNotFoundException.class)
예외처리에 대한 부분은 사람마다 다르게 구현하는 것 같은데요!
제가 선호하는 방법은

```
interface ErrorStatus {
  HttpStatus getStatus();
  String getMessage();
}

enum ErrorCode implements ErrorStatus {
  INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR),
  MEMBER_NOT_FOUND(HttpStatus.BAD_REQUEST);
  ~
}

class CustomException extends RuntimeException {
  ErrorStatus status;
  ~
}

class AnotherCustomException extends RuntimeException implements ErrorStatus {
  ~
}
```

이러한 방식으로 설계해두고 사용하는 것 같습니다!
기본적인 예외처리의 경우 ErrorCode를 사용한 예외처리를 사용하고,
메시지가 복잡하거나 특별한 케이스를 나타내는 예외처리의 경우는 Exception을 만들어 2가지 방법으로 사용할 수 있도록요!

2020-06-02 13:39 UTC, jaeyeonling commented on src/main/java/wooteco/subway/web/FavoritesController.java
> +@RequestMapping("members/favorites")
LoginMember는 로그인 한 유저를 나타내고, PathVariable로는 조회할 대상을 나타낸다고 보시면 되는데요.
RESTful 에서는 URL에 Resource를 표현하는 것이 원칙입니다.
지금은 내 정보만 조회하지만, 추후 다른 유저의 정보를 조회할 상황이 발생할 수도 있겠네요~!
RESTful 이전 API들은 기능에 1:1 매칭하여 기능을 구현했었다는 것을 생각하며 어떠한 장점이 있을지 고민해보면 좋을 것 같습니다.

2020-06-03 04:44 UTC, ParkDooWon commented on src/main/java/wooteco/subway/web/FavoritesController.java
> +@RequestMapping("members/favorites")
로그인한 유저가 아닌 다른 유저를 조회할 수도 있다는 생각을 못했네요. 😅
RESTful의 장점에 대해 더 생각해보겠습니다. 좋은 피드백 감사합니다! :)

2020-06-03 08:49 UTC, ParkDooWon commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +            .orElseThrow(IllegalArgumentException::new);
제가 아무런 메세지도 적지않았네요.. 😢 
상황에 대한 메세지를 추가해보았습니다! :)

2020-06-03 08:57 UTC, ParkDooWon commented on src/main/java/wooteco/subway/web/ExceptionController.java
> +	@ExceptionHandler(EntityNotFoundException.class)
제안해주신 방법을 참고해서 비슷한 방법으로 에러를 전달하도록 변경해보았습니다. :)
아직 예외 처리가 익숙하지않아 연습으로 `enum으로 에러를 관리하는 방법`과 `Custom Exception으로 예외를 처리하는 방법`을 둘 다 사용해보았습니다. :)

2020-06-04 12:35 UTC, jaeyeonling approved these changes
수 많은 피드백을 반영하시느라 고생 많으셨습니다 💯 
해당 요청은 머지하도록 하겠습니다!

2020-06-04 12:35 UTC, jaeyeonling commented on src/main/java/wooteco/subway/exception/LineNotFoundException.java
> +    private String errorMessage = "존재하지 않는 노선입니다.";
큰 차이는 없겠지만 static으로 관리해주셔도 괜찮겠네요!

2020-06-04 12:35 UTC, merged