[로운] JPA 미션 제출합니다.
woowacourse/atdd-subway-favorite pull request #59
Opened 2020-06-18 00:32 UTC by lowoon

계속해서 리팩토링 해나가겠습니다.

2020-06-18 12:46 UTC, woowahan-pjs requested changes
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
다음 리뷰 요청 때는 Merge 하도록 하겠습니다.

2020-06-18 12:46 UTC, woowahan-pjs commented on src/main/java/wooteco/subway/domain/line/Line.java
>      private LocalDateTime updatedAt;
아래의 글을 읽고 Audit 기능을 적용해 보세요.
https://umanking.github.io/jpa-audit

2020-06-18 12:46 UTC, woowahan-pjs commented on src/main/java/wooteco/subway/service/line/LineService.java
> +        lineStationService.deleteLineStationByStationId(stationId);
다른 노선의 지하철 역도 지우는 것이 맞나요?

2020-06-24 04:38 UTC, lowoon commented on src/main/java/wooteco/subway/domain/line/Line.java
>      private LocalDateTime updatedAt;
수정했습니다!

2020-06-24 04:39 UTC, lowoon commented on src/main/java/wooteco/subway/service/line/LineService.java
> +        lineStationService.deleteLineStationByStationId(stationId);
이 부분에 대해서 궁금한 점이 생겼는데 `lineStationService`내에서 `lineStationRepository.deleteAllByStationId`를 호출했는데 이렇게 되면 StationId가 같은 모든 LineStation들을 삭제해주지 않나요??

2020-06-24 05:22 UTC, woowahan-pjs commented on src/main/java/wooteco/subway/service/line/LineService.java
> +        lineStationService.deleteLineStationByStationId(stationId);
특정 노선의 지하철 역만 지우고 싶은 것 아닌가요?

2020-06-24 05:45 UTC, lowoon commented on src/main/java/wooteco/subway/service/line/LineService.java
> +        lineStationService.deleteLineStationByStationId(stationId);
아 생각해보니 그러네요!
station을 삭제하는 부분과 헷갈렸던 것 같습니다!
말씀하신대로 수정했습니다.

2020-06-24 05:54 UTC, woowahan-pjs approved these changes
Spring Data JPA로 바꾸느라 대단히 고생 많으셨습니다. 🥇 
이만 Merge 하겠습니다.

2020-06-24 05:54 UTC, merged