[라빈] API 테스트/문서자동화 미션 제출합니다
woowacourse/atdd-subway-favorite pull request #9
Opened 2020-05-26 08:52 UTC by giantim

감사합니다!

2020-05-27 14:10 UTC, jihan805 requested changes
안녕하세요 깔끔하게 구현 잘하셨어요 💯 
피드백 남겼으니 확인해주세요!

2020-05-27 14:10 UTC, jihan805 commented on src/test/java/wooteco/subway/acceptance/member/LoginMemberAcceptanceTest.java
> +        TokenResponse tokenResponse = login(TEST_USER_EMAIL, TEST_USER_PASSWORD);
토큰 획득에 실패하는 경우에 대한 테스트도 추가해보면 어떨까요?

2020-05-27 14:10 UTC, jihan805 commented on src/main/java/wooteco/subway/service/favorite/FavoriteService.java
> +    private boolean isDuplicate(Long memberId, Favorite favorite) {
1. 어떤 중복인지 메서드에 나타내도 좋을 것 같아요 !
2. 해당 클래스에도 transactional 을 적용할 수 있는 부분이 있는지 확인해보면 어떨까요?

2020-05-27 14:10 UTC, jihan805 commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +            throw new DuplicateEmailException();
DbActionExecutionException 이 발생하는 모든 경우에 대해 DuplicateEmailException를 던져주는 것이 적절할까요?

2020-05-27 14:10 UTC, jihan805 commented on src/test/java/wooteco/subway/service/member/MemberServiceTest.java
> +    void createMemberWithDuplicateEmail() {
예외에 대한 테스트 👍 
update등에 대한 테스트도 추가하면 어떨까요?

2020-05-27 14:10 UTC, jihan805 commented on src/main/java/wooteco/subway/web/ExceptionController.java
> +    public ResponseEntity<ErrorResponse> getDuplicateKeyException(RuntimeException exception) {
ExceptionHandler에 정의되지 않은 에러가 발생하는 경우에 대한 처리도 추가하면 어떨까요?

2020-05-27 14:10 UTC, jihan805 commented on src/main/java/wooteco/subway/web/FavoriteController.java
> +    @PostMapping("/favorites")
/favorites 가 반복되는데 RequestMapping에 대해 찾아보면 어떨까요?

2020-05-28 04:04 UTC, giantim commented on src/main/java/wooteco/subway/service/favorite/FavoriteService.java
> +    private boolean isDuplicate(Long memberId, Favorite favorite) {
메서드 명을 더 구체적으로 바꾸고 transactional 을 추가했습니다 :)

2020-05-28 13:16 UTC, giantim commented on src/main/java/wooteco/subway/service/member/MemberService.java
> +            throw new DuplicateEmailException();
피드백 주신 내용을 보고서 다시 생각을 해보니 reposiroty 에서 save 를 실행할 때 DbActionExcutionException 이 아닌 다른 예외도 발생할 수 있는데 현재는 DbActionExcutionException 에 대해서만 예외 처리를 하고 있고 그에 대해서 이메일 중복에 관한 커스텀 예외를 던지고 있는 것이 적절하지 않다는 생각이 드네요!
ExceptionHandler 에 정의되지 않은 에러를 처리하는 핸들러를 추가하고 repository 에서 save 를 실행할 때 발생하는 에러를 처리하는 방법은 괜찮은 설계가 될지 궁금합니다 :)

2020-05-30 13:51 UTC, jihan805 commented on src/main/java/wooteco/subway/domain/favorite/Favorite.java
> +    private String departure;
역 이름을 사용한다면 역이름이 바뀌는 경우 찾지 못하는 경우가 생길 수 있을 것 같아요!

2020-06-02 12:11 UTC, jihan805 approved these changes
안녕하세요, 피드백 반영 모두 잘해주셨네요 👍 
머지할게요, 고생 많으셨습니다!

2020-06-02 12:11 UTC, merged